### ISSUE TITLE
Style Form

### ISSUE THREAD

**Issue by eduskx** [eduskx/hammerhart#72]
## Value proposition
As a DIY enthusiast
I want to have an appealing Form
In order to increase UX 
## Description
![image](https://github.com/user-attachments/assets/e7dcbf1e-ee8e-4984-b281-efdc18f05d04)
## Acceptance criteria
- Form has a fixed header and footer section
    - header includes a title and close button
    - footer includes a submit button; maybe a cancel/clear button too
- Form has a scrollable main section
## Tasks
- [ ] Create a `styling/form` branch
- [ ] Adjust the sections of the Form to match the AC
- [ ] Implement styling

**Comment by SylvieDoumet** [comment]
Rethink the colors (text, textfields) - the contrasts is quite low (not so good for accessibility, ex. "Rot-grün-schwäche")

Make a difference between UI / UX Design in your US 

Rethink who is your user - an appealing form is quite different according to the user group you choose - be more precise in the task you're describing
